// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_EveryMind.Data;

#nullable disable

namespace Project_EveryMind.Migrations
{
    [DbContext(typeof(ProdutoDataContext))]
    partial class ProdutoDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_EveryMind.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CodigoProduto");

                    b.Property<string>("DescriçãoProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("DescriçãoProduto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("PrecoProduto")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("PrecoProduto");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodigoProduto" }, "IX_Produto_Codigo")
                        .IsUnique();

                    b.ToTable("Produto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
